services:
  server:
    build:
      context: ./server
    networks:
      - monitoring_net
    environment:
      - CLIENTS=client1,client2,client3,client4,client5
    cap_add:
      - NET_ADMIN

  client1:
    build:
      context: ./client
    networks:
      - monitoring_net
    environment:
      - SERVER=server
    cap_add:
      - NET_ADMIN

  client2:
    build:
      context: ./client
    networks:
      - monitoring_net
    environment:
      - SERVER=server
    cap_add:
      - NET_ADMIN

  client3:
    build:
      context: ./client
    networks:
      - monitoring_net
    environment:
      - SERVER=server
    cap_add:
      - NET_ADMIN

  client4:
    build:
      context: ./client
    networks:
      - monitoring_net
    environment:
      - SERVER=server
    cap_add:
      - NET_ADMIN

  client5:
    build:
      context: ./client
    networks:
      - monitoring_net
    environment:
      - SERVER=server
    cap_add:
      - NET_ADMIN

networks:
  monitoring_net: